### ISSUE TITLE
清明节上坟及贡品通知

### ISSUE THREAD

**Issue by wolfogre** [SHU-PV-Blue/Issues#10]
昨天朱老师说了三个任务和一个福利，
# 任务：
1. 帮其他学院爬一个网站的数据[Materials Project](https://www.materialsproject.org/)  
   这事主要由周王负责，所以他写软件说明书的任务归我，且之后分配任务尽量少分配给他；
2. 由任务1而起，注册并登陆任务1的网站，随便选几个元素，搜材料，点击任一结果，查看材料，朱老师堆页面中的三维交互动画很感兴趣：
   ![2](https://cloud.githubusercontent.com/assets/9418365/14242122/2a106baa-fa82-11e5-858e-b9c53eeec90f.PNG)
   ![3](https://cloud.githubusercontent.com/assets/9418365/14242123/2a1bce96-fa82-11e5-8bc1-71584769548e.PNG)
   朱老师希望我们探究一下这玩意儿的技术路径。  
3. 与主线任务有关，汪老师买了一个气象数据库，以应用程序的方式给的。我们需要学一下windows hook，用程序模拟人操作程序，再探取控件属性获取数据，把整个数据库搞下来。
# 福利：

以后每个月有三个福利：
1. 以小组为单位，1000元上限的出租车发票报销，这个大家就随便报吧，有就报；
2. 以小组为单位，300元上限的图书发票，平均下来一人60；
3. 以小组为单位，300元上限的计算机配件发票，平均下来一人60；

除出租车发票，发票抬头必须是上海大学。所有发票给我就行。

**Comment by zhaokuohaha** [comment]
领了任务2
