### ISSUE TITLE
大学主页布局调查

### ISSUE THREAD

**Issue by wolfogre** [SHU-PV-Blue/Issues#23]
干活了。
# 任务描述

朱老师要调查一下国外国内大学主页的布局情况，要的东西有：主页布局的示意图，主页有哪些板块。
# 目前情况

我写了个网站，能够看各个大学的主页截图，可在线上传主页布局的示意图和修改板块说明。现在需要大家查看各个网站的主页截图（桌面版），绘制主页布局的示意图，说明主页有哪些板块。
因为是示意图，只要能说明布局情况就行。采用颜色矩形表示不同内容：
- 菜单，底部导航：黑色
- 图片，视频：蓝色
- 图文：绿色
- 文字：红色
- 列表：黄色
- 若出现不没有预料到的内容，联系我。

不要太长，可以省略重复的内容。如果觉得有应该修改的地方一起讨论。
# 工作流程
1. 访问http://cake.wolfogre.com:8080/uhp/
2. 进入管理员模式：http://cake.wolfogre.com:8080/uhp?admin=密码（密码在群里说）
3. 管理源模式下，布局里有上传按钮，板块里有更新按钮；
4. 查看主页主页截图桌面版，使用画图（或其他工具），绘制绘制主页布局的示意图；
5. 上传主页布局的示意图，注意是jpg格式
6. 编写板块说明，即主页上有哪些板块，点击更新按钮。
7. 退出管理员模式：重启浏览器或访问http://cake.wolfogre.com:8080/uhp?admin=随便错误密码
# 任务分工

我已经做了哈佛大学和加州大学伯克利分校，这个是反面教材，做得不能比我更差了……

接下来我要继续维护网站，协助大家，所以我偷个懒，不给自己分配任务了。

朝增：4~10；
永华：11~17；
王舒：18~24；
周王：24~30；
子华：31~37。

有困难我会帮忙。

**Comment by zhaokuohaha** [comment]
在颜色框里`标注`板块内容估计好一点

**Comment by wolfogre** [comment]
你试一下看看，我主要怕工作量增大 @zhaokuohaha
